
services:
  app:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql:
