
services:
  app:
    build: .
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: telegram_ecommerce
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: mysql -h localhost --password=$DB_PASSWORD --execute "select version();"
      interval: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql:
